### ISSUE TITLE
scope-go-{date-guid}.log files are generated beside *_test.go source files if /var/log/scope doesn't exist or is not writeable

### ISSUE THREAD

**Issue by fshot** [undefinedlabs/scope-go-agent#174]
When running `make test` on a project that includes the scope go agent, scope log files are written to disk alongside the go source files, if the SCOPE_LOG_ROOT_PATH env isn't set, and the default /var/log/scope directory isn't present or isn't writable by the `make` process.

User experience would be better if these were not written, or were written to a tmp folder.

**Comment by tonyredondo** [comment]
Hi @fshot, thanks for reporting this issue, could you tell us which version of the agent are you running? A similar issue were resolved in https://github.com/undefinedlabs/scope-go-agent/pull/151 and released in https://github.com/undefinedlabs/scope-go-agent/releases/tag/0.1.11, currently the latest version is v0.1.12. Could you try with the latest version to confirm there still a problem with the log path?

The current behavior is to try to record in `/var/log/scope` and if the agent can't write, ask to OS for the temp folder.
