### ISSUE TITLE
InContainer is false on Docker run

### ISSUE THREAD

**Issue by drodriguezhdez** [undefinedlabs/scope-go-agent#200]
Project: https://github.com/scope-demo/containered-test
Scope link: https://app.scope.dev/dashboard/b774c8da-2494-4ede-8d2f-b0321ff3cd7c/400412c1-517f-4f94-8291-7cc167d92ca4/default/explore/inspect/941d1ca5faebb6382d277029a9835db186919327/00000000-0000-0000-5704-36a977be1630/trace?spanId=00000000-0000-0000-669c-40be8d4c6d0a

Actual: `incointaner: false`. Expected: `incontainer: true`.

![image](https://user-images.githubusercontent.com/29516565/76854697-dbf20d80-684f-11ea-9b15-307a3ab13d75.png)

**Comment by tonyredondo** [comment]
I have to reproduce it first, I ran the docker container and the results are the expected:

![image](https://user-images.githubusercontent.com/69803/76882440-f1c8f800-687a-11ea-9a27-c5b5a2c0ec56.png)
