### ISSUE TITLE
Test duration takes into account when test is paused

### ISSUE THREAD

**Issue by drodriguezhdez** [undefinedlabs/scope-go-agent#209]
https://app.scope.dev/dashboard/b774c8da-2494-4ede-8d2f-b0321ff3cd7c/39e30602-0315-4df0-9aaf-02056c77a312/default/explore/inspect/fa9f5b32b3b86c34dbe146aade6b74848508b5d2/00000000-0000-0000-0a69-76194bf8410d/trace

**Comment by tonyredondo** [comment]
Closed by #214
