### ISSUE TITLE
Instrumentation of gopkg.check Suites

### ISSUE THREAD

**Issue by drodriguezhdez** [undefinedlabs/scope-go-agent#217]
In `docker/distribution` repository, they're using Test Suites from (https://godoc.org/gopkg.in/check.v1#TestingT)

Example: https://github.com/scope-demo/distribution/blob/master/configuration/configuration_test.go

Check if this Suites can be instrumented with Scope agent

**Comment by tonyredondo** [comment]
Duplicate #49
