### ISSUE TITLE
Allow in-code configuration of the Scope agent

### ISSUE THREAD

**Issue by fermayo** [undefinedlabs/scope-go-agent#39]
Allow the user to create a new agent in code, passing all configuration options to `NewAgent()`

**Comment by tonyredondo** [comment]
All configuration options? There are a lot that maybe doesn't make sense like `CurrentFolder`, `Hostname`, `Git diff`, `PlatformName` ...

I was thinking something like `ApiKey`, `ApiEndpoint`, `Service`, Maybe the tracer, or a recorder to decorate.

I don't know, what do you think?

**Comment by fermayo** [comment]
> All configuration options? There are a lot that maybe doesn't make sense like `CurrentFolder`, `Hostname`, `Git diff`, `PlatformName` ...
> 
> I was thinking something like `ApiKey`, `ApiEndpoint`, `Service`, Maybe the tracer, or a recorder to decorate.
> 
> I don't know, what do you think?

The ones that make sense, like in the other agents.
